services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/var/app
    ports:
      - "5000:5000"
    command: pipenv run api
  batch:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/var/app
    command: tail -f /dev/null
