name: "Schedule event"

on:
  schedule:
    - cron: "0 9 * * 1,6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generate_model
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup pipenv
        run: pip install pipenv

      - name: Cache virtualenvs
        uses: actions/cache@v4
        id: generate_model_cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.OS }}-lib-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.generate_model_cache.outputs.cache-hit != 'true'
        run: pipenv install -d

      - name: Execute
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: pipenv run start
